### ISSUE TITLE
C 컴파일 / 디버깅 / make 사용법 학습

### ISSUE THREAD

**Issue by kugorang** [KraftonJungle4th/Classroom4_Week04_Team5_StudyNotes#5]

**Comment by kugorang** [comment]
선애님께서 MacOS용 Docker 세팅 방법에 대해 정리해주시기로 하여 Assignees로 추가

**Comment by ifindary** [comment]
## Docker 설정 방법(MacOS 기준)

- Docker 설치 및 로그인
- (이미지 생성) Dockerfile이 담긴 폴더에서 해당 명령어 입력. docker build -t k-ubuntu .
ㄴ Dockerfile은 슬랙에서 만석님이 공유해 주신 파일로 설치
ㄴ 이때 인증 관련 오류가 난다면 sudo vi ~/.docker/config.json 파일에서 "credsStore": ""으로 수정, 도커 재시작
- (컨테이너 생성 및 실행) docker run -it --name 'krafton-ubuntu' k-ubuntu /bin/bash
ㄴ 만약 컨테이너에서 나왔을 경우, 컨테이너 재접속 하는 명령어 docker exec -it krafton-ubuntu /bin/bash
- (연결을 원하는 폴더에서) docker run -v `pwd`:/projects -it --name c-projects k-ubuntu /bin/bash 

원하는 깃 레포지트리가 있다면 가져오기

vs code
- 버전은 1.85로 다운 (https://code.visualstudio.com/updates/v1_85)
- Docker, Dev containers 익스텐션 설치
- 연결했던 폴더로 접근

**Comment by kugorang** [comment]
Windows에서 VS Code에 GCC를 사용하는 C 컴파일 환경 구축하는 방법을 정리

***

# GCC 설치

- [Microsoft에서 제공하는 공식 문서](https://code.visualstudio.com/docs/cpp/config-mingw)를 확인하면 설치가 쉬웠음
- 처음에는 WSL을 고려하지 않아 WIndows용 make를 설치했으나 WSL 사용으로 인해 직접적인 사용은 해보지 않음
  - [윈도우(Windows)에서 make 명령 사용하기](https://ndb796.tistory.com/381)

# GCC 디버깅 설정

- vscode에서 제공하는 gcc 컴파일러의 기준으로 launch.json
