### ISSUE TITLE
동적 메모리 할당 이론 정리

### ISSUE THREAD

**Issue by kugorang** [KraftonJungle4th/Classroom4_Week04_Team5_StudyNotes#6]
메모리 등의 컴퓨터 하드웨어 관점에서 동적 메모리 할당 학습을 설명해야 함

**Comment by kugorang** [comment]
다음주 월요일(2/5)에 퀴즈 대비를 할 때 같이 정리하기로 하여 보류로 이동

**Comment by moonmisae118** [comment]
# 동적 메모리 할당
- 실행 중(런타임)에 사용할 메모리 공간을 할당하는 것을 의미한다.
- 정적 할당(static allocation)
    - 프로그램이 실행되기 위해서는 메모리가 필요한데 컴파일러는 컴파일 시점에 소스 코드를 읽고 변수 타입들의 크기에 따라 메모리를 할당한다.

- 동적 할당(dynamic allocation)
    - 컴파일 타임이 아닌 프로그램 런타임에 필요한 만큼의 메모리 공간을 확보하는 것을 의미한다.

- 동적 할당이 필요한 이유
    - 사용할 때마다 필요한 만큼만 메모리 공간을 확보하고 다 사용했다면, free시켜줌으로써 메모리 공간을 해제해 한정된 메모리 공간을 효율적으로 사용할 수 있게 된다.
    - 함수가 종료되거나 변수의 영역을 벗어나면 자동으로 메모리가 해제되는 정적 할당은 스택에 저장된다. 하지만 동적 할당은 힙에 저장이 된다.

- 힙(heap) 영역
    - 보다 큰 크기의 데이터를 담고자 동적으로 할당하는 메모리 공간을 지칭한다.
    - 즉, 힙 영역에 필요할 때마다 메모리 공간을 할당하고, 더 이상 필요하지 않을 경우 메모리를 해제해주는 과정을 동적 할당이라고 한다.
    - 장점
        - 상황에 따라 원하는 크기의 메모리가 할당되므로 경제적이다(malloc or calloc)
        - 이미 할당된 메모리라도 언제든 크기를 조정할 수 있다.(realloc)
    - 단점
        - c언어의 경우 GC(Garbage Collector)가 없기 때문에 개발자가 직접 메모리를 해제해줘야 한다.(free) 그렇지 않으면, 메모리 누수가 나타난다.
        
- 메모리 할당
    - 프로그램이 실행되는 동안 메모리 공간을 동적으로 할당하거나 해제하는 과정을 동적 메모리 할당(dynamic memory allocation)이라고 부르며, 필요한 만큼의 메모리를 실행 중인 프로그램이 할당 받을 수 있게 한다.

**Comment by ifindary** [comment]
lckm 👍

**Comment by kugorang** [comment]
안녕하세요, (G)PT 선생님께 첨삭 받은 내용을 공유드립니다.


> # 동적 메모리 할당
> * 정적 할당(static allocation)

* 정적 할당은 프로그램이 실행되는 동안 할당된 메모리 크기가 변경될 수 없다는 점을 명확히 해주면 좋음
* 즉, 컴파일 시 결정된 메모리 크기는 프로그램 실행 동안 고정되어 있음


> * 동적 할당(dynamic allocation)

* 동적 할당을 사용하면 메모리의 크기를 프로그램 실행 중에 조정할 수 있다는 점을 강조
* 이는 프로그램의 유연성을 높여줌


> * 힙(heap) 영역

* 스택 영역과 달리 개발자가 직접 메모리 할당과 해제를 관리해야 하며, 이는 스택 영역보다 메모리 관리에 있어 더 많은 유연성과 책임을 요구한다는 점을 추가 설명
* 힙 영역에서 메모리를 할당하고 해제하는 과정은 시스템 호출(**system call**)을 통해 운영체제의 메모리 관리 시스템과 상호 작용


>   * 단점
>     
>     * c언어의 경우 GC(Garbage Collector)가 없기 때문에 개발자가 직접 메모리를 해제해줘야 한다.(free) 그렇지 않으면, 메모리 누수가 나타난다.

* "메모리 누수"를 "메모리 누수(memory leak)"로 표현하면서, 메모리 누수가 프로그램의 성능 저하나 시스템의 안정성 문제를 일으킬 수 있음
* 메모리 할당과 해제를 관리하는 과정에서 오류가 발생하기 쉬움
* 예를 드면, 이미 해제된 메모리에 접근하는 dangling pointer 문제나 메모리 할당 실패로 인한 예외 처리 필요성 등
