### ISSUE TITLE
균형 이진 탐색트리 이론 정리

### ISSUE THREAD

**Issue by kugorang** [KraftonJungle4th/Classroom4_Week04_Team5_StudyNotes#8]
- [x] 개념
- [ ] 삽입
- [ ] 삭제

**Comment by moonmisae118** [comment]
# 균형 이진 탐색 트리
- 모든 노드에 대해 해당 노드의 왼쪽 서브 트리와 오른쪽 서브 트리의 높이 차이가 많아야 1인 이진 탐색 트리의 한 종류이다.
- 대표적으로 AVL 트리와, Red-Black 트리가 있다.

## AVL 트리
![Image](https://github.com/KraftonJungle4th/Classroom4_Week04_Team5_rbtree-lab/assets/115637701/cff3abc9-bef7-4a58-829a-175aa29a59ee)

- 노드의 삽입과 삭제가 일어날 때 균형을 체크하고 유지하는 트리
- BF(Balance Factor) : 왼쪽 서브 트리 높이 - 오른쪽 서브 트리 높이를 각 노드의 BF를 [-1, 0, 1]만 가지게 하여 균형을 유지한다.

- AVL 트리 리밸런싱
    - 균형이 깨졌을 때
        - BF가 +면 왼쪽 서브 트리에 이상이 있다.
        - BF가 -면 오른쪽 서브 트리에 이상이 있다.
    - 회전 연산
        - 단순 회전 : LL, RR
            - LL(Left-Left) : 회전 1회, 오른쪽 방향으로 회전
![Image](https://github.com/KraftonJungle4th/Classroom4_Week04_Team5_rbtree-lab/assets/115637701/75a01b4f-ba1c-4959-a421-0734f2555840)

            - RR(Right-Right) : 회전 1회, 왼쪽 방향으로 회전
![Image](https://github.com/KraftonJungle4th/Classroom4_Week04_Team5_rbtree-lab/assets/115637701/28360a88-443e-4915-b144-9e973d3a696f)

            - 이중 회전 : LR, RL
              - LR(Left-Right) : 회전 2회, RR 회전 후 LL 회전
![Image](https://github.com/KraftonJungle4th/Classroom4_Week04_Team5_rbtree-lab/assets/115637701/b2e97ee6-995e-498b-b03f-4ecaa693f937)

              - RL(Right-Left) : 회전 2회, LL 회전 후 RR 회전
              ![Image](https://github.com/KraftonJungle4th/Classroom4_Week04_Team5_rbtree-lab/assets/115637701/73960bbb-b55e-4357-9840-bbef328fc2e1)

**Comment by ifindary** [comment]
깔끔한 설명과 그림 덕분에 이해가 잘 되었습니다. 👍

**Comment by kugorang** [comment]
LCKM 👍 
***
제가 작성한 내용도 첨부해둡니다 :)

1. [이진 트리 (Binary Trees)](https://github.com/KraftonJungle4th/Classroom4_Week04_Team5_rbtree-lab/wiki/%EC%9D%B4%EC%A7%84-%ED%8A%B8%EB%A6%AC-(Binary-Trees))
2. [이진 탐색 트리 (Binary Search Trees, BST)](https://github.com/KraftonJungle4th/Classroom4_Week04_Team5_rbtree-lab/wiki/%EC%9D%B4%EC%A7%84-%ED%83%90%EC%83%89-%ED%8A%B8%EB%A6%AC-(Binary-Search-Trees,-BST))
3. [균형 이진 트리의 종류](https://github.com/KraftonJungle4th/Classroom4_Week04_Team5_rbtree-lab/wiki/%EA%B7%A0%ED%98%95-%EC%9D%B4%EC%A7%84-%ED%8A%B8%EB%A6%AC%EC%9D%98-%EC%A2%85%EB%A5%98)
