### ISSUE TITLE
레드블랙트리 이론 정리

### ISSUE THREAD

**Issue by kugorang** [KraftonJungle4th/Classroom4_Week04_Team5_StudyNotes#9]
- [x] 개념
- [x] 삽입
- [x] 삭제

**Comment by ifindary** [comment]
보류 사유: 기초적인 이론은 학습한 상태. 영상을 보고 월요일에 구현하면서 미흡한 이론이 있다면 보충하기로 논의함.

**Comment by kugorang** [comment]
레드-블랙 트리 관련 내용을 위키에 모두 정리 완료

https://github.com/KraftonJungle4th/Classroom4_Week04_Team5_rbtree-lab/wiki
